"""migration 基盤の DDL テスト."""

import asyncio
from collections.abc import Iterator
from pathlib import Path
import uuid

from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
import asyncpg
import pytest

from apps.api.core.db_url import to_plain_dsn, with_database
from scripts.common.db_test_settings import get_db_test_settings
from scripts.db.init_test_db import create_baseline_extensions

pytestmark = pytest.mark.on_schema_change

PROJECT_ROOT = Path(__file__).resolve().parents[3]

# **既定値は持たない**。base URL は test context の必須
# `DATABASE_URL` だけから来る。欠落は `ValidationError` として落ち、localhost の
# DSN へ fallback しない。alembic へ渡す URL は SQLAlchemy 形式
# （`postgresql+asyncpg://`）、asyncpg に直接渡す DSN は素の `postgresql://`。


async def _execute(dsn: str, statement: str) -> None:
    """管理用 DB に 1 文だけ流す."""
    conn = await asyncpg.connect(to_plain_dsn(dsn))
    try:
        await conn.execute(statement)
    finally:
        await conn.close()


async def _fetch_column(dsn: str, query: str) -> list[str]:
    """1 列だけの SELECT を文字列のリストとして返す."""
    conn = await asyncpg.connect(to_plain_dsn(dsn))
    try:
        rows = await conn.fetch(query)
    finally:
        await conn.close()
    return [str(row[0]) for row in rows]


def alembic_config() -> Config:
    """`migrations/` を指す Alembic `Config` を組み立てる.

    **接続先はここでは渡さない**。`-x db_url=` は撤去したので、
    `migrations/env.py` は `DB_ENV_CONTEXT` が選ぶ context の `DATABASE_URL` を
    読む。使い捨て DB を指すときは `monkeypatch.setenv("DATABASE_URL", ...)` を
    使う（`env.py` は同一 process 内で `os.environ` を読む）。

    Returns:
        `migrations/` を指す Config。
    """
    cfg = Config(str(PROJECT_ROOT / "alembic.ini"))
    cfg.set_main_option("script_location", str(PROJECT_ROOT / "migrations"))
    # pytest の log capture を潰さないため、env.py の fileConfig を抑止する。
    cfg.attributes["configure_logger"] = False
    return cfg


@pytest.fixture
def empty_database(monkeypatch: pytest.MonkeyPatch) -> Iterator[str]:
    """migration を 1 本も当てていない使い捨て DB を作って渡す.

    「空」とは **`init-db.sql` が用意するベースラインの状態**（拡張だけ入っていて
    テーブルは無い）を指す。実際の `app_dev` / `app_test` がその状態から始まる以上、
    拡張の無い DB で試しても現実の初期状態を再現したことにならない。

    teardown の `WITH (FORCE)` は残存接続を切ってから drop する（PostgreSQL 13+）。
    テスト本体が DB を壊れた状態で残しても drop は成立するので、後続に連鎖しない。

    Yields:
        使い捨て DB を指す SQLAlchemy 形式の URL。
    """
    base_url = str(get_db_test_settings().database_url)
    db_name = f"app_migtest_{uuid.uuid4().hex[:12]}"
    disposable_url = with_database(base_url, db_name)
    # CREATE / DROP DATABASE はトランザクション内で実行できず、対象 DB 自身にも
    # 接続できないので、メンテナンス DB (postgres) 経由で発行する。
    maintenance_url = with_database(base_url, "postgres")

    asyncio.run(_execute(maintenance_url, f'CREATE DATABASE "{db_name}"'))
    try:
        asyncio.run(create_baseline_extensions(to_plain_dsn(disposable_url)))
        # `migrations/env.py` は選択 context の `DATABASE_URL` を読む。使い捨て DB は
        # DSN を argv へ載せず、この process の environment で指す。
        monkeypatch.setenv("DATABASE_URL", disposable_url)
        yield disposable_url
    finally:
        asyncio.run(
            _execute(
                maintenance_url, f'DROP DATABASE IF EXISTS "{db_name}" WITH (FORCE)'
            )
        )


def test_upgrade_head_creates_schema_on_empty_db(empty_database: str) -> None:
    """空 DB に `upgrade head` 1 本で会話・run のテーブルができる."""
    command.upgrade(alembic_config(), "head")

    tables = asyncio.run(
        _fetch_column(
            empty_database,
            "SELECT table_name FROM information_schema.tables "
            "WHERE table_schema = 'public'",
        )
    )

    assert {"conversations", "runs"} <= set(tables), (
        f"migration が会話・run のテーブルを作っていません: {sorted(tables)}"
    )


def test_no_drift_between_orm_and_migrations(empty_database: str) -> None:  # noqa: ARG001
    """migration を当てた DB と ORM 定義の間に差分が無い.

    差分が出るのは「ORM を変えたのに migration を書いていない」ときで、
    そのまま進むと **dev の DB とコードだけが一致し、空から作った DB では動かない**
    という形で表面化する。`alembic check` はその状態をここで赤にする。
    """
    config = alembic_config()
    command.upgrade(config, "head")

    try:
        command.check(config)
    except AutogenerateDiffsDetected as exc:
        pytest.fail(
            "ORM（apps/api/db/base.py の Base.metadata）と migration に差分があります。"
            "`DB_ENV_CONTEXT=test uv run alembic revision --autogenerate -m '...'` で "
            f"migration を追加してください:\n{exc}"
        )


def test_revision_scripts_import_without_an_operations_context() -> None:
    """revision スクリプトが **module スコープで `op.*` を呼んでいない**.

    `op` は Operations context が確立されて初めて使えるプロキシで、
    `alembic history` / `heads` / `show` / **`revision`** は context を張らずに
    revision スクリプトを import するだけ。module スコープで `op.f(...)` などを
    呼ぶと、そこで

        NameError: Can't invoke function 'f', as the proxy object has not yet
        been established for the Alembic 'Operations' class.

    になり、**revision の探索と次の migration の生成が全部できなくなる**。

    **上の 2 本ではこれを検出できない。** `upgrade` も `check` も context を
    張ってから import するので、module スコープの `op.*` は通ってしまう。

    DB は要らない（スクリプトを読むだけ）が、`on_schema_change` に置いてある ——
    見ている対象が migration スクリプトそのものだから。
    """
    # **URL は要らない**（script directory を読むだけ）。
    script = ScriptDirectory.from_config(alembic_config())

    # `walk_revisions()` は revision map を組み立てる = 全スクリプトを import する。
    revisions = [revision.revision for revision in script.walk_revisions()]

    assert revisions, "revision が 1 本も見つかりません"
    assert script.get_current_head() is not None
